name: Prisma Migration

on:
  push:
    branches:
      - main

jobs:
  migrate:
    name: Generate and Apply Migration
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Prisma
        run: npm install prisma@latest -g

      - name: Install dependencies
        run: npm install

      - name: Get commit message
        id: commit_msg
        run: echo "::set-output name=message::$(git log -1 --pretty=format:'%s')"

      - name: Replace spaces with underscores
        id: formatted_msg
        run: echo "::set-output name=message::${{ steps.commit_msg.outputs.message//' '/_ }}"

      - name: Generate Prisma Migration
        run: npx prisma migrate dev --name "${{ steps.formatted_msg.outputs.message }}"
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}

      - name: Apply Prisma Migration
        run: npx prisma migrate deploy
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
