name: Prisma Migration

on:
  push:
    branches:
      - main

jobs:
  migrate:
    name: Generate and Apply Migration
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install Prisma
        run: npm install prisma@latest -g

      - name: Install dependencies
        run: npm install

      - name: Generate Prisma Migration
        run: npx prisma migrate deploy
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
