name: Prisma Migration

on:
  push:
    branches:
      - main

jobs:
  migrate:
    name: Generate and Apply Migration
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install Prisma
        run: npm install prisma@latest -g

      - name: Install dependencies
        run: npm install

      - name: Get commit message
        id: commit_msg
        run: echo "::set-output name=message::$(git log -1 --pretty=format:'%s')"

      - name: Check commit message for keyword
        id: skip_ci
        run: echo "::set-output name=skip::$(echo "${{ steps.commit_msg.outputs.message }}" | grep -ci '[ci skip]')"

      - name: Replace spaces with underscores
        id: formatted_msg
        run: echo "::set-output name=message::${{ steps.commit_msg.outputs.message }} | tr ' ' '_'"

      - name: Generate Prisma Migration
        run: npx prisma migrate dev --name "${{ steps.formatted_msg.outputs.message }}"
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}

      - name: Save migration files
        if: ${{ steps.skip_ci.outputs.skip != '1' }}
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add prisma/migrations
          git commit -m "Add migration: ${{ steps.formatted_msg.outputs.message }}"
          git push
        working-directory: .
